Shopping cart
shumYevh/BookWeb pull request #12
Opened 2024-05-22 17:33 UTC by shumYevh

2024-05-23 07:04 UTC, Vasul-Pankiv requested changes

2024-05-23 07:04 UTC, Vasul-Pankiv commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    @Transactional
why you make get method transactional?

2024-05-23 09:16 UTC, shumYevh commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    @Transactional
LazyInit

2024-05-23 09:20 UTC, shumYevh commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    @Transactional
I fix this by Join fetch in the next commit

2024-05-23 09:46 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/ShoppingCartController.java
> +@RequestMapping(value = "/api/cart")
```suggestion
@RequestMapping("/cart")
```
Add `server.servlet.context-path=/api` in application.properties

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto getShoppingCart() {
```suggestion
    public ShoppingCartResponseDto getShoppingCart(Authentication authentication) {
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/ShoppingCartController.java
> +        String userName = SecurityContextHolder.getContext().getAuthentication().getName();
```suggestion
        User user = (User) authentication.getPrincipal();
        return shoppingCartService.getShoppingCart(user.getId());
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/ShoppingCartController.java
> +        String email = SecurityContextHolder.getContext().getAuthentication().getName();
the same as above.
Check other places

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/ShoppingCartController.java
> +
```suggestion
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/dto/shopping/cart/AddCartItemDto.java
> +public class AddCartItemDto {
```suggestion
public class CartItemRequestDto {
```
You can use java record for DTO

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/mapper/CartItemMapper.java
> +public interface CartItemMapper {
```suggestion
public interface CartItemMapper {
    CartItem toCartItem(CartItemRequestDto cartItemDto);

    @Mapping(source = "book.id", target = "bookId")
    @Mapping(source = "book.title", target = "bookTitle")
    CartItemResponseDto toDto(CartItem cartItem);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/mapper/ShoppingCartMapper.java
> +@Mapper(config = MapperConfig.class)
```suggestion
@Mapper(config = MapperConfig.class, uses = CartItemMapper.class)
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/mapper/ShoppingCartMapper.java
> +    @Mapping(source = "user.id", target = "userId")
```suggestion
    @Mapping(source = "user.id", target = "userId")
    ShoppingCartResponseDto toDto(ShoppingCart shoppingCart);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/mapper/ShoppingCartMapper.java
> +    CartItemResponseDto toCartItemResponseDto(CartItem cartItem);
remove

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/ShoppingCart.java
> +    @OneToMany (mappedBy = "shoppingCart", orphanRemoval = true)
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/ShoppingCart.java
> +    @OneToOne
You can use
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/repository/shopping/cart/CartItemRepository.java
> +    Optional<CartItem> findCartItemById(Long cartId);
It's better to use 
```suggestion
    Optional<CartItem> findByIdAndShoppingCartId(Long itemId, Long cartId);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/repository/shopping/cart/ShoppingCartRepository.java
> +    @Query("SELECT cart FROM ShoppingCart cart LEFT JOIN FETCH cart.cartItems")
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/repository/shopping/cart/ShoppingCartRepository.java
> +    ShoppingCart findByUser(User userId);
```suggestion
    ShoppingCart findByUser(Long userId);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +        return shoppingCartRepository.save(shoppingCart);
```suggestion
        ShoppingCart shoppingCart = new ShoppingCart();
        shoppingCart.setUser(user);
        shoppingCartRepository.save(shoppingCart);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    public ShoppingCart createShoppingCart(ShoppingCart shoppingCart) {
```suggestion
    public ShoppingCart createShoppingCart(User user) {
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toShoppingCartResponseDto(
```suggestion
       return shoppingCartMapper.toDto(shoppingCartRepository.findByUserId(userId));
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto getShoppingCart(String email) {
```suggestion
    public ShoppingCartResponseDto getShoppingCart(Long userId) {
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/repository/shopping/cart/ShoppingCartRepository.java
> +    ShoppingCart findShoppingCartByUserEmail(@Param("email") String email);
You can remove this method and find shopping cart by userId

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findShoppingCartByUserEmail(email);
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto addCartItem(AddCartItemDto addCartItemDto, String email) {
```suggestion
    public ShoppingCartResponseDto addCartItem(AddCartItemDto addCartItemDto, Long userId) {
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(cartItemId).orElseThrow(
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(updateCartItemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        cartItemRepository.save(cartItem);
        return shoppingCartMapper.toDto(cart);
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto updateCartItem(String email,
```suggestion
    public ShoppingCartResponseDto updateCartItem(Long userId,
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findCartItemById(cartItemId).orElseThrow(
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, shoppingCart.getId())....
```

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/shopping/cart/ShoppingCartServiceImpl.java
> +public class ShoppingCartServiceImpl implements ShoppingCartService {
Add `@Tramsactional` where is needed

2024-05-23 09:46 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/user/UserServiceImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
Refactor the logic according to the comments in ShoppingCartServiceImpl class

2024-05-23 16:52 UTC, okuzan requested changes
make sure to fix all comments, maybe you skipped those?
![image](https://github.com/shumYevh/BookWeb/assets/49767049/7c847c3d-2cc5-4ecb-a6a4-c02ccfd78bf0)

2024-05-23 16:52 UTC, okuzan commented on src/main/java/org/example/bookweb/models/ShoppingCart.java
> +    @OneToOne
not fixed

2024-05-23 16:52 UTC, okuzan commented on src/main/java/org/example/bookweb/models/ShoppingCart.java
> +    @OneToMany (mappedBy = "shoppingCart", orphanRemoval = true)
not fixed

2024-05-23 16:52 UTC, okuzan commented on src/main/java/org/example/bookweb/repository/shopping/cart/CartItemRepository.java
> +    Optional<CartItem> findCartItemById(Long cartId);
not fixed

2024-05-24 06:40 UTC, Vasul-Pankiv approved these changes

2024-05-24 14:35 UTC, merged