Orders
shumYevh/BookWeb pull request #13
Opened 2024-05-28 21:52 UTC by shumYevh

2024-05-29 14:26 UTC, MAMentorFX requested changes

2024-05-29 14:26 UTC, MAMentorFX commented on src/main/java/org/example/bookweb/controller/OrderController.java
> +            description = "")
add summary and description

2024-05-29 14:26 UTC, MAMentorFX commented on src/main/java/org/example/bookweb/controller/OrderController.java
> +        User user = (User) authentication.getPrincipal();
extract to local method

2024-05-30 06:31 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/OrderController.java
> +@RequestMapping(value = "/orders")
```suggestion
@RequestMapping("/orders")
```

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/OrderController.java
> +                                                     @PathVariable Long orderId) {
```suggestion
                                                     @PathVariable @Positive Long orderId) {
```
And add `@Validated` under the controller

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/OrderController.java
> +                                                     @PathVariable Long orderId) {
Check other places

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/Order.java
> +
remove blank lines

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/models/OrderItem.java
> +
```suggestion
```

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/order/OrderServiceImpl.java
> +        Order.Status statusEnum = Order.Status.fromString(statusUpdateRequest.getStatus());
```suggestion
        Order order = orderRepository.findById(orderId)
                .map(o -> {
                    o.setStatus(Status.valueOf(orderDto.status()));
                    return o;
                })
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order with id: %d not found", orderId)
                ));
        return orderMapper.toUpdateDto(orderRepository.save(order));
```

Where 
```
@Mapping(target = "orderId", source = "id")
UpdateOrderResponseDto toUpdateDto(Order order);
```

So you don't need fromString() method

2024-05-30 06:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/service/order/OrderServiceImpl.java
> +        return orderItemMapper.toDto(orderItemRepository.findOrderItemByIdAndOrderIdAndUserId(
To increase readability let's use
```suggestion
        OrderItem item = orderItemRepository.findByIdAndOrderIdAndUserId(orderItemId, orderId, userId)
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order item: %d not found in order: %d for user: %d",
                                orderItemId, orderId, userId)
                ));
        return orderItemMapper.toOrderItemDto(item);
```

2024-05-30 19:23 UTC, sarakhmen approved these changes

2024-05-30 21:19 UTC, merged