BookServiceTests
shumYevh/BookWeb pull request #15
Opened 2024-06-09 16:35 UTC by shumYevh

2024-06-25 14:47 UTC, Vasul-Pankiv requested changes

2024-06-25 14:47 UTC, Vasul-Pankiv commented on src/test/resources/database/book/add_SpringBoot_book_to_books_table.sql
> +VALUES ('Learning Spring Boot', 'John Doe', '9781234567897', 29.99, 'A comprehensive guide to Spring Boot', 'url://spring_boot_cover.jpg', false);
each file has to end with an empty line

2024-06-25 14:47 UTC, Vasul-Pankiv commented on src/test/java/org/example/bookweb/controller/CategoryControllerTest.java
> +                .setDescription("Beautiful books with love"));
create an utility class to provide tests with tests data

2024-06-27 12:32 UTC, MentorMateAcademy requested changes

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/controller/BookControllerTest.java
> +    }
Private method after public

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual, "id");
```suggestion

        MvcResult result = mockMvc.perform(post("/books")
                        .content(jsonRequest)
                        .contentType(MediaType.APPLICATION_JSON)
                )
                .andExpect(status().isCreated())
                .andReturn();

        //When
        BookDto actual = objectMapper
                .readValue(result.getResponse().getContentAsString(), BookDto.class);
        //Then
        EqualsBuilder.reflectionEquals(expected, actual, "id");
```

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual, "id");
Fix all tests by this pattern

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/controller/BookControllerTest.java
> +                .setCoverImage("url://NEW_TestCoverImage");
Save values to constants and reuse this

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/controller/BookControllerTest.java
> +        String testBookTitle = "Test Title";
only given you write, use same style

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/service/BookServiceTest.java
> +
```suggestion
```

2024-06-27 12:32 UTC, MentorMateAcademy commented on src/test/java/org/example/bookweb/utils/TestDataUtil.java
> +                .setCoverImage("url://TestCoverImage");
Constants

2024-06-27 19:59 UTC, sarakhmen approved these changes

2024-06-28 09:03 UTC, merged