implementedSearchBook
shumYevh/BookWeb pull request #2
Opened 2024-04-16 13:59 UTC by shumYevh

2024-04-16 18:18 UTC, Vasul-Pankiv requested changes

2024-04-16 18:18 UTC, Vasul-Pankiv commented on src/main/java/org/example/bookweb/repository/BookSpecificationBuilder.java
> +            spec = spec.and(bookProviderManager.getSpecificationProvider("title")
better to make spec_key a constant

2024-04-16 18:18 UTC, Vasul-Pankiv commented on src/main/java/org/example/bookweb/repository/book/AuthorSpecificationProvider.java
> +                -> root.get("author").in(Arrays.stream(params).toArray());
```suggestion
                -> root.get(KEY).in(Arrays.stream(params).toArray());
```

2024-04-16 18:18 UTC, Vasul-Pankiv commented on src/main/java/org/example/bookweb/repository/book/IsbnSpecificationProvider.java
> +                -> root.get("isbn").in(Arrays.stream(params).toArray());
same

2024-04-16 18:18 UTC, Vasul-Pankiv commented on src/main/java/org/example/bookweb/repository/book/TitleSpecificationProvider.java
> +                -> root.get("title").in(Arrays.stream(params).toArray());
same

2024-04-17 08:59 UTC, kozhukhovsky approved these changes

2024-04-17 10:00 UTC, merged