ImplementedLoginAndAddedToSwagger
shumYevh/BookWeb pull request #9
Opened 2024-05-15 17:11 UTC by shumYevh

2024-05-16 06:22 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/controller/BookController.java
>      @GetMapping("/search")
Should we add `@PreAuthorize` here?

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```
use constant from Spring

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_HEADER)) {
```

private static final String TOKEN_HEADER = "Bearer ";

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/AuthenticationService.java
> +
```suggestion
```

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/JwtAuthenticationFilter.java
> +
```suggestion
```

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/JwtUtil.java
> +
```suggestion
```

2024-05-16 06:22 UTC, Elena-Bruyako commented on src/main/java/org/example/bookweb/security/JwtUtil.java
> +
```suggestion
```

2024-05-16 16:45 UTC, shumYevh commented on src/main/java/org/example/bookweb/controller/BookController.java
>      @GetMapping("/search")
I am not sure

2024-05-17 06:14 UTC, Elena-Bruyako approved these changes
Good job!

2024-05-17 10:03 UTC, merged